CREATE TABLE `water_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`slug` varchar(120) NOT NULL,
	`shortDescription` varchar(500),
	`imageUrl` text,
	`icon` varchar(50),
	`sortOrder` int NOT NULL DEFAULT 0,
	`visibleEnPublico` int NOT NULL DEFAULT 1,
	`status` enum('active','inactive') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `water_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `water_categories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `water_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`email` varchar(320) NOT NULL,
	`province` varchar(100),
	`city` varchar(100),
	`housingType` varchar(100),
	`productId` int,
	`productName` varchar(200),
	`observations` text,
	`acceptPrivacy` int NOT NULL DEFAULT 0,
	`status` enum('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',
	`internalNotes` text,
	`clientId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `water_inquiries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `water_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(200) NOT NULL,
	`slug` varchar(120) NOT NULL,
	`subtitle` varchar(300),
	`categoryId` int,
	`secondaryCategories` text,
	`shortDescription` varchar(500),
	`longDescription` text,
	`claimsHighlighted` text,
	`benefits` text,
	`forWhom` text,
	`priceVisible` varchar(100),
	`priceFrom` varchar(100),
	`priceOrientative` varchar(200),
	`mainImage` text,
	`galleryImages` text,
	`badge` varchar(100),
	`badgeColor` varchar(50),
	`technicalSpecs` text,
	`installationText` text,
	`maintenanceText` text,
	`warrantyText` text,
	`bulletAdvantages` text,
	`whyChooseBlock` text,
	`expertBlock` text,
	`faqBlock` text,
	`testimonialsBlock` text,
	`trustBlock` text,
	`ctaPrimaryLabel` varchar(100) DEFAULT 'Reservar sistema',
	`ctaSecondaryLabel` varchar(100) DEFAULT 'Conocer más detalles',
	`seoTitle` varchar(200),
	`seoDescription` varchar(400),
	`sortOrder` int NOT NULL DEFAULT 0,
	`visibleEnPublico` int NOT NULL DEFAULT 1,
	`destacadoEnHome` int NOT NULL DEFAULT 0,
	`productoPrincipal` int NOT NULL DEFAULT 0,
	`status` enum('active','inactive') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `water_products_id` PRIMARY KEY(`id`),
	CONSTRAINT `water_products_slug_unique` UNIQUE(`slug`)
);
