/**
 * CRM — Formulario de Servicio (crear / editar)
 * Incluye campos de detalle: descripción larga, beneficios, qué incluye,
 * contraindicaciones e imagen de detalle.
 */

import { useState, useEffect } from "react";
import { useLocation, useParams } from "wouter";
import { ArrowLeft, Save, Loader2, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import CRMLayout from "@/components/CRMLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ImageUploader } from "@/components/ImageUploader";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type FormData = {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  price: string;
  durationMinutes: number;
  durationLabel: string;
  type: "consulta" | "masaje" | "otro";
  modality: "online" | "presencial" | "ambos";
  imageUrl: string;
  // Campos de detalle
  detailImage: string;
  longDescription: string;
  benefits: string[];
  includes: string[];
  contraindications: string;
  featured: boolean;
  status: "active" | "inactive";
  sortOrder: number;
};

const EMPTY: FormData = {
  slug: "",
  name: "",
  shortDescription: "",
  description: "",
  price: "",
  durationMinutes: 60,
  durationLabel: "",
  type: "consulta",
  modality: "ambos",
  imageUrl: "",
  detailImage: "",
  longDescription: "",
  benefits: ["", "", ""],
  includes: ["", "", ""],
  contraindications: "",
  featured: false,
  status: "active",
  sortOrder: 0,
};

// Genera un slug desde un nombre
function toSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 80);
}

function parseJsonArray(raw: string | null | undefined): string[] {
  if (!raw) return ["", "", ""];
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed.length > 0 ? parsed : ["", "", ""];
    return ["", "", ""];
  } catch { return ["", "", ""]; }
}

export default function ServicioForm() {
  const params = useParams<{ id?: string }>();
  const [, navigate] = useLocation();
  const isEdit = !!params.id && params.id !== "nuevo";
  const serviceId = isEdit ? parseInt(params.id!) : null;
  const [form, setForm] = useState<FormData>(EMPTY);
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!isEdit);
  const utils = trpc.useUtils();

  // Cargar slugs existentes para mostrar en el campo
  const { data: allServices } = trpc.services.listAdmin.useQuery();
  const existingSlugs = (allServices ?? []).map((s) => s.slug);

  // Cargar datos si es edición
  const { data: existing, isLoading: loadingExisting } = trpc.services.get.useQuery(
    { id: serviceId! },
    { enabled: isEdit && !!serviceId }
  );

  useEffect(() => {
    if (existing) {
      setForm({
        slug: existing.slug,
        name: existing.name,
        shortDescription: existing.shortDescription ?? "",
        description: existing.description ?? "",
        price: existing.price ?? "",
        durationMinutes: existing.durationMinutes ?? 60,
        durationLabel: existing.durationLabel ?? "",
        type: (["consulta", "masaje", "otro"] as const).includes(existing.type as any)
          ? (existing.type as FormData["type"])
          : "consulta",
        modality: (["online", "presencial", "ambos"] as const).includes(existing.modality as any)
          ? (existing.modality as FormData["modality"])
          : "ambos",
        imageUrl: existing.imageUrl ?? "",
        detailImage: (existing as any).detailImage ?? "",
        longDescription: (existing as any).longDescription ?? "",
        benefits: parseJsonArray((existing as any).benefits),
        includes: parseJsonArray((existing as any).includes),
        contraindications: (existing as any).contraindications ?? "",
        featured: existing.featured === 1,
        status: existing.status as FormData["status"],
        sortOrder: existing.sortOrder,
      });
    }
  }, [existing]);

  const createMutation = trpc.services.create.useMutation({
    onSuccess: () => {
      utils.services.listAdmin.invalidate();
      toast.success("Servicio creado correctamente");
      navigate("/crm/servicios");
    },
    onError: (err) => {
      const msg = err.message || "";
      if (msg.includes("Duplicate entry") || msg.includes("unique") || msg.includes("slug")) {
        setErrors((prev) => ({ ...prev, slug: `El slug "${form.slug}" ya existe. Usa uno diferente.` }));
        toast.error(`El slug "${form.slug}" ya está en uso. Cambia el identificador.`);
      } else {
        toast.error(msg || "Error al crear el servicio");
      }
    },
  });

  const updateMutation = trpc.services.update.useMutation({
    onSuccess: () => {
      utils.services.listAdmin.invalidate();
      toast.success("Servicio actualizado correctamente");
      navigate("/crm/servicios");
    },
    onError: (err) => toast.error(err.message || "Error al actualizar el servicio"),
  });

  function validate(): boolean {
    const e: typeof errors = {};
    if (!form.slug.trim()) e.slug = "El slug es obligatorio";
    if (!/^[a-z0-9_]+$/.test(form.slug)) e.slug = "Solo letras minúsculas, números y guiones bajos";
    const slugsToCheck = isEdit
      ? existingSlugs.filter(s => s !== existing?.slug)
      : existingSlugs;
    if (slugsToCheck.includes(form.slug)) {
      e.slug = `El slug "${form.slug}" ya está en uso. Prueba con "${form.slug}_2" u otro identificador.`;
    }
    if (!form.name.trim()) e.name = "El nombre es obligatorio";
    if (form.price && !/^\d+(\.\d{1,2})?$/.test(form.price)) e.price = "Formato inválido (ej: 90 o 90.00)";
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    // Filtrar items vacíos de arrays
    const cleanBenefits = form.benefits.filter(b => b.trim());
    const cleanIncludes = form.includes.filter(i => i.trim());

    const data = {
      slug: form.slug.trim(),
      name: form.name.trim(),
      shortDescription: form.shortDescription.trim() || undefined,
      description: form.description.trim() || undefined,
      price: form.price.trim() || null,
      durationMinutes: form.durationMinutes,
      durationLabel: form.durationLabel.trim() || undefined,
      type: (["consulta", "masaje", "otro"] as const).includes(form.type) ? form.type : "consulta",
      modality: (["online", "presencial", "ambos"] as const).includes(form.modality) ? form.modality : "ambos",
      imageUrl: form.imageUrl.trim() || null,
      detailImage: form.detailImage.trim() || null,
      longDescription: form.longDescription.trim() || null,
      benefits: cleanBenefits.length > 0 ? JSON.stringify(cleanBenefits) : null,
      includes: cleanIncludes.length > 0 ? JSON.stringify(cleanIncludes) : null,
      contraindications: form.contraindications.trim() || null,
      featured: form.featured,
      status: form.status,
      sortOrder: form.sortOrder,
    };

    if (isEdit && serviceId) {
      updateMutation.mutate({ id: serviceId, data });
    } else {
      createMutation.mutate(data);
    }
  }

  function set<K extends keyof FormData>(key: K, value: FormData[K]) {
    setForm((prev) => {
      const updated = { ...prev, [key]: value };
      if (key === "name" && slugAutoGenerated) {
        updated.slug = toSlug(value as string);
      }
      return updated;
    });
    if (errors[key]) setErrors((prev) => ({ ...prev, [key]: undefined }));
  }

  function handleSlugChange(raw: string) {
    const cleaned = raw.toLowerCase().replace(/[^a-z0-9_]/g, "_");
    setSlugAutoGenerated(false);
    set("slug", cleaned);
  }

  function updateArrayItem(field: "benefits" | "includes", index: number, value: string) {
    setForm((prev) => {
      const arr = [...prev[field]];
      arr[index] = value;
      return { ...prev, [field]: arr };
    });
  }

  function addArrayItem(field: "benefits" | "includes") {
    setForm((prev) => ({ ...prev, [field]: [...prev[field], ""] }));
  }

  function removeArrayItem(field: "benefits" | "includes", index: number) {
    setForm((prev) => {
      const arr = prev[field].filter((_, i) => i !== index);
      return { ...prev, [field]: arr.length > 0 ? arr : [""] };
    });
  }

  const isPending = createMutation.isPending || updateMutation.isPending;

  if (isEdit && loadingExisting) {
    return (
      <CRMLayout>
        <div className="flex items-center justify-center h-64 text-stone-400 text-sm">
          <Loader2 size={20} className="animate-spin mr-2" /> Cargando servicio...
        </div>
      </CRMLayout>
    );
  }

  return (
    <CRMLayout>
      <div className="p-6 max-w-2xl mx-auto space-y-6">
        {/* Cabecera */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/crm/servicios")}
            className="p-2 rounded-lg text-stone-400 hover:text-stone-700 hover:bg-stone-50 transition-colors"
          >
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="text-xl font-semibold text-stone-800">
              {isEdit ? "Editar servicio" : "Nuevo servicio"}
            </h1>
            <p className="text-xs text-stone-400">
              {isEdit ? "Modifica los datos del servicio" : "Añade un nuevo servicio a la web"}
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-8">

          {/* ── SECCIÓN 1: Datos básicos ── */}
          <div className="bg-white rounded-xl border border-stone-100 p-6 space-y-5">
            <h2 className="text-sm font-semibold text-stone-700 border-b border-stone-100 pb-3">
              Datos básicos
            </h2>

            {/* Nombre */}
            <div className="space-y-1.5">
              <Label htmlFor="name">Nombre del servicio *</Label>
              <Input
                id="name"
                value={form.name}
                onChange={(e) => set("name", e.target.value)}
                placeholder="Masaje Terapéutico"
                className={errors.name ? "border-red-300" : ""}
              />
              {errors.name && <p className="text-xs text-red-500">{errors.name}</p>}
            </div>

            {/* Slug */}
            <div className="space-y-1.5">
              <Label htmlFor="slug">
                Slug (identificador interno) *
                <span className="text-xs text-stone-400 ml-2 font-normal">
                  Se genera automáticamente — puedes editarlo manualmente
                </span>
              </Label>
              <div className="relative">
                <Input
                  id="slug"
                  value={form.slug}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  placeholder="masaje_terapeutico"
                  className={`font-mono text-sm pr-20 ${errors.slug ? "border-red-300" : ""}`}
                />
                {slugAutoGenerated && !isEdit && (
                  <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-stone-400 bg-stone-50 px-1 rounded">
                    auto
                  </span>
                )}
              </div>
              {errors.slug && <p className="text-xs text-red-500">{errors.slug}</p>}
              {existingSlugs.length > 0 && (
                <p className="text-xs text-stone-400">
                  Slugs en uso: {existingSlugs.filter(s => !isEdit || s !== existing?.slug).join(", ")}
                </p>
              )}
            </div>

            {/* Descripción corta */}
            <div className="space-y-1.5">
              <Label htmlFor="shortDesc">
                Descripción corta
                <span className="text-xs text-stone-400 ml-2 font-normal">Visible en la tarjeta del listado</span>
              </Label>
              <Input
                id="shortDesc"
                value={form.shortDescription}
                onChange={(e) => set("shortDescription", e.target.value)}
                placeholder="Técnica combinada de equilibrio energético y masaje con aceites esenciales."
                maxLength={500}
              />
            </div>

            {/* Precio y duración */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label htmlFor="price">Precio (€)</Label>
                <Input
                  id="price"
                  value={form.price}
                  onChange={(e) => set("price", e.target.value)}
                  placeholder="90 (vacío = a consultar)"
                />
                {errors.price && <p className="text-xs text-red-500">{errors.price}</p>}
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="durationMin">Duración (minutos)</Label>
                <Input
                  id="durationMin"
                  type="number"
                  min={1}
                  value={form.durationMinutes}
                  onChange={(e) => set("durationMinutes", parseInt(e.target.value) || 60)}
                />
              </div>
            </div>

            {/* Etiqueta de duración */}
            <div className="space-y-1.5">
              <Label htmlFor="durationLabel">
                Etiqueta de duración
                <span className="text-xs text-stone-400 ml-2 font-normal">
                  Texto visible (ej: "60 min", "Mínimo 60 min")
                </span>
              </Label>
              <Input
                id="durationLabel"
                value={form.durationLabel}
                onChange={(e) => set("durationLabel", e.target.value)}
                placeholder="60 min"
              />
            </div>

            {/* Tipo y modalidad */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label>Tipo</Label>
                <Select value={form.type} onValueChange={(v) => set("type", v as FormData["type"])}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="consulta">Consulta</SelectItem>
                    <SelectItem value="masaje">Masaje</SelectItem>
                    <SelectItem value="otro">Otro</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label>Modalidad</Label>
                <Select value={form.modality} onValueChange={(v) => set("modality", v as FormData["modality"])}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ambos">Presencial / Online</SelectItem>
                    <SelectItem value="online">Solo Online</SelectItem>
                    <SelectItem value="presencial">Solo Presencial</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Imagen principal */}
            <ImageUploader
              label="Imagen principal (tarjeta del listado)"
              value={form.imageUrl}
              onChange={(url) => set("imageUrl", url)}
              hint="JPG, PNG, WEBP hasta 20 MB"
            />

            {/* Estado, orden y destacado */}
            <div className="grid grid-cols-3 gap-4">
              <div className="space-y-1.5">
                <Label>Estado</Label>
                <Select value={form.status} onValueChange={(v) => set("status", v as FormData["status"])}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Activo</SelectItem>
                    <SelectItem value="inactive">Inactivo</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="sortOrder">Orden</Label>
                <Input
                  id="sortOrder"
                  type="number"
                  min={0}
                  value={form.sortOrder}
                  onChange={(e) => set("sortOrder", parseInt(e.target.value) || 0)}
                />
              </div>
              <div className="space-y-1.5">
                <Label>Destacado</Label>
                <div className="flex items-center gap-2 h-10">
                  <input
                    type="checkbox"
                    id="featured"
                    checked={form.featured}
                    onChange={(e) => set("featured", e.target.checked)}
                    className="w-4 h-4 accent-[oklch(0.45_0.1_140)]"
                  />
                  <label htmlFor="featured" className="text-sm text-stone-600 cursor-pointer">
                    Mostrar como popular
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* ── SECCIÓN 2: Contenido de la página de detalle ── */}
          {form.type !== "otro" && (
          <div className="bg-white rounded-xl border border-stone-100 p-6 space-y-5">
            <div className="border-b border-stone-100 pb-3">
              <h2 className="text-sm font-semibold text-stone-700">Página de detalle</h2>
              <p className="text-xs text-stone-400 mt-0.5">
                Este contenido aparece en{" "}
                <code className="bg-stone-100 px-1 rounded">
                  /{form.type === "masaje" ? "masajes" : "consultas"}/{form.slug || "slug"}
                </code>
              </p>
            </div>

            {/* Descripción larga */}
            <div className="space-y-1.5">
              <Label htmlFor="longDesc">
                Descripción completa
                <span className="text-xs text-stone-400 ml-2 font-normal">Texto principal de la ficha de detalle</span>
              </Label>
              <Textarea
                id="longDesc"
                value={form.longDescription}
                onChange={(e) => set("longDescription", e.target.value)}
                placeholder="Describe en detalle la sesión, la técnica utilizada, qué puede esperar el cliente, los resultados habituales..."
                rows={6}
              />
            </div>

            {/* Imagen de detalle */}
            <ImageUploader
              label="Imagen de detalle (opcional)"
              value={form.detailImage}
              onChange={(url) => set("detailImage", url)}
              hint="Imagen adicional para la ficha de detalle. JPG, PNG, WEBP hasta 20 MB"
            />

            {/* Beneficios / Ideal para */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>
                  {form.type === "consulta" ? "Ideal para (beneficiarios)" : "Beneficios"}
                  <span className="text-xs text-stone-400 ml-2 font-normal">Uno por línea — aparecen como lista con check</span>
                </Label>
                <button
                  type="button"
                  onClick={() => addArrayItem("benefits")}
                  className="inline-flex items-center gap-1 text-xs text-[oklch(0.45_0.1_140)] hover:underline"
                >
                  <Plus size={12} /> Añadir
                </button>
              </div>
              <div className="space-y-2">
                {form.benefits.map((benefit, i) => (
                  <div key={i} className="flex gap-2">
                    <Input
                      value={benefit}
                      onChange={(e) => updateArrayItem("benefits", i, e.target.value)}
                      placeholder={`Beneficio ${i + 1} (ej: Reduce el estrés y la tensión)`}
                      className="flex-1"
                    />
                    {form.benefits.length > 1 && (
                      <button
                        type="button"
                        onClick={() => removeArrayItem("benefits", i)}
                        className="p-2 text-stone-400 hover:text-red-500 transition-colors"
                      >
                        <Trash2 size={14} />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Qué incluye */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>
                  ¿Qué incluye la sesión?
                  <span className="text-xs text-stone-400 ml-2 font-normal">Aparece en el sidebar de reserva</span>
                </Label>
                <button
                  type="button"
                  onClick={() => addArrayItem("includes")}
                  className="inline-flex items-center gap-1 text-xs text-[oklch(0.45_0.1_140)] hover:underline"
                >
                  <Plus size={12} /> Añadir
                </button>
              </div>
              <div className="space-y-2">
                {form.includes.map((item, i) => (
                  <div key={i} className="flex gap-2">
                    <Input
                      value={item}
                      onChange={(e) => updateArrayItem("includes", i, e.target.value)}
                      placeholder={`Incluye ${i + 1} (ej: Evaluación inicial de necesidades)`}
                      className="flex-1"
                    />
                    {form.includes.length > 1 && (
                      <button
                        type="button"
                        onClick={() => removeArrayItem("includes", i)}
                        className="p-2 text-stone-400 hover:text-red-500 transition-colors"
                      >
                        <Trash2 size={14} />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Contraindicaciones / Notas */}
            <div className="space-y-1.5">
              <Label htmlFor="contraindications">
                {form.type === "consulta" ? "Notas importantes / Garantía" : "Contraindicaciones / Notas importantes"}
                <span className="text-xs text-stone-400 ml-2 font-normal">Opcional — aparece con icono de aviso</span>
              </Label>
              <Textarea
                id="contraindications"
                value={form.contraindications}
                onChange={(e) => set("contraindications", e.target.value)}
                placeholder={
                  form.type === "consulta"
                    ? "Ej: Si no quedas satisfecho te haré devolución..."
                    : "Ej: No recomendado durante el embarazo, en caso de fiebre o infecciones activas..."
                }
                rows={3}
              />
            </div>
          </div>
          )}

          {/* Botones */}
          <div className="flex gap-3">
            <Button
              type="submit"
              disabled={isPending}
              className="gap-2 bg-[oklch(0.45_0.1_140)] hover:bg-[oklch(0.38_0.1_140)] text-white"
            >
              {isPending ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}
              {isEdit ? "Guardar cambios" : "Crear servicio"}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/crm/servicios")}
            >
              Cancelar
            </Button>
          </div>
        </form>
      </div>
    </CRMLayout>
  );
}
