/**
 * CRM — Formulario de Servicio (crear / editar)
 */

import { useState, useEffect } from "react";
import { useLocation, useParams } from "wouter";
import { ArrowLeft, Save, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import CRMLayout from "@/components/CRMLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ImageUploader } from "@/components/ImageUploader";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type FormData = {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  price: string;
  durationMinutes: number;
  durationLabel: string;
  type: "consulta" | "masaje" | "otro";
  modality: "online" | "presencial" | "ambos";
  imageUrl: string;
  featured: boolean;
  status: "active" | "inactive";
  sortOrder: number;
};

const EMPTY: FormData = {
  slug: "",
  name: "",
  shortDescription: "",
  description: "",
  price: "",
  durationMinutes: 60,
  durationLabel: "",
  type: "consulta",
  modality: "ambos",
  imageUrl: "",
  featured: false,
  status: "active",
  sortOrder: 0,
};

// Genera un slug desde un nombre
function toSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 80);
}

export default function ServicioForm() {
  const params = useParams<{ id?: string }>();
  const [, navigate] = useLocation();
  const isEdit = !!params.id && params.id !== "nuevo";
  const serviceId = isEdit ? parseInt(params.id!) : null;
  const [form, setForm] = useState<FormData>(EMPTY);
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!isEdit);
  const utils = trpc.useUtils();

  // Cargar slugs existentes para mostrar en el campo
  const { data: allServices } = trpc.services.listAdmin.useQuery();
  const existingSlugs = (allServices ?? []).map((s) => s.slug);

  // Cargar datos si es edición
  const { data: existing, isLoading: loadingExisting } = trpc.services.get.useQuery(
    { id: serviceId! },
    { enabled: isEdit && !!serviceId }
  );

  useEffect(() => {
    if (existing) {
      setForm({
        slug: existing.slug,
        name: existing.name,
        shortDescription: existing.shortDescription ?? "",
        description: existing.description ?? "",
        price: existing.price ?? "",
        durationMinutes: existing.durationMinutes ?? 60,
        durationLabel: existing.durationLabel ?? "",
        type: existing.type as FormData["type"],
        modality: existing.modality as FormData["modality"],
        imageUrl: existing.imageUrl ?? "",
        featured: existing.featured === 1,
        status: existing.status as FormData["status"],
        sortOrder: existing.sortOrder,
      });
    }
  }, [existing]);

  const createMutation = trpc.services.create.useMutation({
    onSuccess: () => {
      utils.services.listAdmin.invalidate();
      toast.success("Servicio creado correctamente");
      navigate("/crm/servicios");
    },
    onError: (err) => {
      const msg = err.message || "";
      if (msg.includes("Duplicate entry") || msg.includes("unique") || msg.includes("slug")) {
        setErrors((prev) => ({ ...prev, slug: `El slug "${form.slug}" ya existe. Usa uno diferente.` }));
        toast.error(`El slug "${form.slug}" ya está en uso. Cambia el identificador.`);
      } else {
        toast.error(msg || "Error al crear el servicio");
      }
    },
  });

  const updateMutation = trpc.services.update.useMutation({
    onSuccess: () => {
      utils.services.listAdmin.invalidate();
      toast.success("Servicio actualizado correctamente");
      navigate("/crm/servicios");
    },
    onError: (err) => toast.error(err.message || "Error al actualizar el servicio"),
  });

  function validate(): boolean {
    const e: typeof errors = {};
    if (!form.slug.trim()) e.slug = "El slug es obligatorio";
    if (!/^[a-z0-9_]+$/.test(form.slug)) e.slug = "Solo letras minúsculas, números y guiones bajos";
    // Verificar slug duplicado (excluir el propio si es edición)
    const slugsToCheck = isEdit
      ? existingSlugs.filter(s => s !== existing?.slug)
      : existingSlugs;
    if (slugsToCheck.includes(form.slug)) {
      e.slug = `El slug "${form.slug}" ya está en uso. Prueba con "${form.slug}_2" u otro identificador.`;
    }
    if (!form.name.trim()) e.name = "El nombre es obligatorio";
    if (form.price && !/^\d+(\.\d{1,2})?$/.test(form.price)) e.price = "Formato inválido (ej: 90 o 90.00)";
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    const data = {
      slug: form.slug.trim(),
      name: form.name.trim(),
      shortDescription: form.shortDescription.trim() || undefined,
      description: form.description.trim() || undefined,
      price: form.price.trim() || null,
      durationMinutes: form.durationMinutes,
      durationLabel: form.durationLabel.trim() || undefined,
      type: form.type,
      modality: form.modality,
      imageUrl: form.imageUrl.trim() || null,
      featured: form.featured,
      status: form.status,
      sortOrder: form.sortOrder,
    };

    if (isEdit && serviceId) {
      updateMutation.mutate({ id: serviceId, data });
    } else {
      createMutation.mutate(data);
    }
  }

  function set<K extends keyof FormData>(key: K, value: FormData[K]) {
    setForm((prev) => {
      const updated = { ...prev, [key]: value };
      // Auto-generar slug desde el nombre si no ha sido editado manualmente
      if (key === "name" && slugAutoGenerated) {
        updated.slug = toSlug(value as string);
      }
      return updated;
    });
    if (errors[key]) setErrors((prev) => ({ ...prev, [key]: undefined }));
  }

  function handleSlugChange(raw: string) {
    const cleaned = raw.toLowerCase().replace(/[^a-z0-9_]/g, "_");
    setSlugAutoGenerated(false); // El usuario lo edita manualmente
    set("slug", cleaned);
  }

  const isPending = createMutation.isPending || updateMutation.isPending;

  if (isEdit && loadingExisting) {
    return (
      <CRMLayout>
        <div className="flex items-center justify-center h-64 text-stone-400 text-sm">
          <Loader2 size={20} className="animate-spin mr-2" /> Cargando servicio...
        </div>
      </CRMLayout>
    );
  }

  return (
    <CRMLayout>
      <div className="p-6 max-w-2xl mx-auto space-y-6">
        {/* Cabecera */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/crm/servicios")}
            className="p-2 rounded-lg text-stone-400 hover:text-stone-700 hover:bg-stone-50 transition-colors"
          >
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="text-xl font-semibold text-stone-800">
              {isEdit ? "Editar servicio" : "Nuevo servicio"}
            </h1>
            <p className="text-xs text-stone-400">
              {isEdit ? "Modifica los datos del servicio" : "Añade un nuevo servicio a la web"}
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5 bg-white rounded-xl border border-stone-100 p-6">
          {/* Nombre */}
          <div className="space-y-1.5">
            <Label htmlFor="name">Nombre del servicio *</Label>
            <Input
              id="name"
              value={form.name}
              onChange={(e) => set("name", e.target.value)}
              placeholder="Consulta Naturópata"
              className={errors.name ? "border-red-300" : ""}
            />
            {errors.name && <p className="text-xs text-red-500">{errors.name}</p>}
          </div>

          {/* Slug */}
          <div className="space-y-1.5">
            <Label htmlFor="slug">
              Slug (identificador interno) *
              <span className="text-xs text-stone-400 ml-2 font-normal">
                Se genera automáticamente desde el nombre — puedes editarlo manualmente
              </span>
            </Label>
            <div className="relative">
              <Input
                id="slug"
                value={form.slug}
                onChange={(e) => handleSlugChange(e.target.value)}
                placeholder="masaje_terapeutico_2"
                className={`font-mono text-sm pr-20 ${errors.slug ? "border-red-300" : ""}`}
              />
              {slugAutoGenerated && !isEdit && (
                <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-stone-400 bg-stone-50 px-1 rounded">
                  auto
                </span>
              )}
            </div>
            {errors.slug && <p className="text-xs text-red-500">{errors.slug}</p>}
            {existingSlugs.length > 0 && (
              <p className="text-xs text-stone-400">
                Slugs en uso: {existingSlugs.filter(s => !isEdit || s !== existing?.slug).join(", ")}
              </p>
            )}
          </div>

          {/* Descripción corta */}
          <div className="space-y-1.5">
            <Label htmlFor="shortDesc">Descripción corta</Label>
            <Input
              id="shortDesc"
              value={form.shortDescription}
              onChange={(e) => set("shortDescription", e.target.value)}
              placeholder="Breve descripción visible en la tarjeta (máx. 500 caracteres)"
              maxLength={500}
            />
          </div>

          {/* Descripción larga */}
          <div className="space-y-1.5">
            <Label htmlFor="desc">Descripción completa</Label>
            <Textarea
              id="desc"
              value={form.description}
              onChange={(e) => set("description", e.target.value)}
              placeholder="Descripción detallada del servicio..."
              rows={5}
            />
          </div>

          {/* Precio y duración */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="price">Precio (€)</Label>
              <Input
                id="price"
                value={form.price}
                onChange={(e) => set("price", e.target.value)}
                placeholder="90 (vacío = a consultar)"
                className={errors.price ? "border-red-300" : ""}
              />
              {errors.price && <p className="text-xs text-red-500">{errors.price}</p>}
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="durationMin">Duración (minutos)</Label>
              <Input
                id="durationMin"
                type="number"
                min={1}
                value={form.durationMinutes}
                onChange={(e) => set("durationMinutes", parseInt(e.target.value) || 60)}
              />
            </div>
          </div>

          {/* Etiqueta de duración */}
          <div className="space-y-1.5">
            <Label htmlFor="durationLabel">
              Etiqueta de duración
              <span className="text-xs text-stone-400 ml-2 font-normal">
                Texto visible (ej: "Mínimo 60 min", "Consulta inicial + 21 días")
              </span>
            </Label>
            <Input
              id="durationLabel"
              value={form.durationLabel}
              onChange={(e) => set("durationLabel", e.target.value)}
              placeholder="60 min"
            />
          </div>

          {/* Tipo y modalidad */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label>Tipo</Label>
              <Select value={form.type} onValueChange={(v) => set("type", v as FormData["type"])}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="consulta">Consulta</SelectItem>
                  <SelectItem value="masaje">Masaje</SelectItem>
                  <SelectItem value="otro">Otro</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Modalidad</Label>
              <Select value={form.modality} onValueChange={(v) => set("modality", v as FormData["modality"])}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ambos">Presencial / Online</SelectItem>
                  <SelectItem value="online">Solo Online</SelectItem>
                  <SelectItem value="presencial">Solo Presencial</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Imagen */}
          <ImageUploader
            label="Imagen del servicio"
            value={form.imageUrl}
            onChange={(url) => set("imageUrl", url)}
            hint="JPG, PNG, WEBP hasta 20 MB"
          />

          {/* Estado, orden y destacado */}
          <div className="grid grid-cols-3 gap-4">
            <div className="space-y-1.5">
              <Label>Estado</Label>
              <Select value={form.status} onValueChange={(v) => set("status", v as FormData["status"])}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Activo</SelectItem>
                  <SelectItem value="inactive">Inactivo</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="sortOrder">Orden</Label>
              <Input
                id="sortOrder"
                type="number"
                min={0}
                value={form.sortOrder}
                onChange={(e) => set("sortOrder", parseInt(e.target.value) || 0)}
              />
            </div>
            <div className="space-y-1.5">
              <Label>Destacado</Label>
              <div className="flex items-center gap-2 h-10">
                <input
                  type="checkbox"
                  id="featured"
                  checked={form.featured}
                  onChange={(e) => set("featured", e.target.checked)}
                  className="w-4 h-4 accent-[oklch(0.45_0.1_140)]"
                />
                <label htmlFor="featured" className="text-sm text-stone-600 cursor-pointer">
                  Mostrar como destacado
                </label>
              </div>
            </div>
          </div>

          {/* Botones */}
          <div className="flex gap-3 pt-2">
            <Button
              type="submit"
              disabled={isPending}
              className="gap-2 bg-[oklch(0.45_0.1_140)] hover:bg-[oklch(0.38_0.1_140)] text-white"
            >
              {isPending ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}
              {isEdit ? "Guardar cambios" : "Crear servicio"}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/crm/servicios")}
            >
              Cancelar
            </Button>
          </div>
        </form>
      </div>
    </CRMLayout>
  );
}
